### ISSUE TITLE
Value of type 'TransitionController' has no member 'present'

### ISSUE THREAD

**Issue by aliasdoc** [naru-jpn/View2ViewTransition#10]
Hi,

I just installed this library using CocoaPods and I have this error, but I use the exactly same code provided by demo project

```
        transitionController.userInfo = ["destinationIndexPath": indexPath, "initialIndexPath": indexPath]
        transitionController.present(viewController: presentedViewController, on: self, attached: presentedViewController, completion: nil)

```
Any idea ??

Thanks.

**Comment by naru-jpn** [comment]
@aliasdoc Can you build and run demo project?
(I want to check that error immediately  but I currently can not run cocoapods in my PC :sad:)

**Comment by aliasdoc** [comment]
Hi @naru-jpn, it's resolved, it was just an older version installer with cocoa pods (0.0.2), just run

```
pod update View2ViewTransition

```
to install last version (0.0.4)
