### ISSUE TITLE
Crashed when presentedView many times swiped until presentingView cell invisible

### ISSUE THREAD

**Issue by fromkk** [naru-jpn/View2ViewTransition#11]
I found crahsed bug.
write some point.
1. Show preview any image.
2. Many times swipe untile presentingView cell invisible
3. Try close
4. Crashed☠

**Comment by naru-jpn** [comment]
@fromkk I can not reproduce this bug😖 
I want to see crash messages if possible!

**Comment by naru-jpn** [comment]
This issue will closed because of inactivation.
