### ISSUE TITLE
Get black screen when cancel interactive transition

### ISSUE THREAD

**Issue by Cantallops** [naru-jpn/View2ViewTransition#22]
```
cancelInteractiveTransition()

let duration: Double = Double(self.duration)*Double(progress)
UIView.animateWithDuration(duration, delay: 0.0, usingSpringWithDamping: 1.0, initialSpringVelocity: 0.0, options: .CurveEaseInOut, animations: {

    self.animationController.destinationTransitionView.frame = self.animationController.destinationFrame
    self.animationController.initialTransitionView.frame = self.animationController.destinationFrame

}, completion: { _ in

    // Cancel Transition
    self.animationController.destinationTransitionView.removeFromSuperview()
    self.animationController.initialTransitionView.removeFromSuperview()

    self.animationController.destinationView.hidden = false
    self.animationController.initialView.hidden = false
    self.transitionController.presentingViewController.view.removeFromSuperview()

    self.transitionContext.completeTransition(false)
})
```

The line `self.transitionController.presentingViewController.view.removeFromSuperview()` in `DismissInteractiveTransition.swift` makes that the app turns black  if you use the root view controller as presentingViewController and the users cancel dismiss and dismiss later.

Comment that line works in my case and I don't know if it affects in other  #cases

I made a pull request with my solution #21

**Comment by naru-jpn** [comment]
@Cantallops I can't see this bug😖
Does this bug occur in example project?

**Comment by Cantallops** [comment]
No I just try it, I use a `UITabBarViewController` as a `PresentingViewController` and presents a `UINavigationController`, the tab bar is the root view controller and it has `UINavigationController`s in `viewControllers` variable. I will investigate a little bit more. 😁

**Comment by naru-jpn** [comment]
@Cantallops I see, I am pleased if you report bug detail!⭐

**Comment by naru-jpn** [comment]
This issue will closed because of inactivation.
