### ISSUE TITLE
Blank screen when comes back from PeekPop

### ISSUE THREAD

**Issue by kronik** [naru-jpn/View2ViewTransition#23]
I've used PeekPop pod to represent a cell and found that when I go back (in UINavigationController) animation ends up with blank screen.

**Comment by naru-jpn** [comment]
@kronik Thanks!
I will check it and fix it if possible😉

**Comment by kronik** [comment]
@naru-jpn any luck?

**Comment by naru-jpn** [comment]
@kronik Not yet.
I want to see your bugging code :thought_balloon:

**Comment by naru-jpn** [comment]
This issue will closed because of inactivation.
