### ISSUE TITLE
UIViewController and UINavigationController 

### ISSUE THREAD

**Issue by alexsanderkhitev** [naru-jpn/View2ViewTransition#26]
Hello! 
If UIViewController has a UINavigationController in this case in this case, does not work does not work. Why? How can fix it?

**Comment by naru-jpn** [comment]
@alexsanderkhitev Hello!🌤
I cannot understand the case `UIViewController has a UINavigationController`.
I want you to explain in specific example (with your source code if possible).

**Comment by naru-jpn** [comment]
Close issue because inactivity.
