### ISSUE TITLE
Using View2View transition between 2 objective-c views

### ISSUE THREAD

**Issue by Datadriven** [naru-jpn/View2ViewTransition#29]
Hi, 

I was wondering if there is a way to use view2viewtransition between 2 objective c views? Basically I want to use this library 2 show transition effect between 2 xib using objective c code. Hope I ma being clear on my question.

Thanks

**Comment by naru-jpn** [comment]
@Datadriven The answer to your question is `may be no way to use from Objective-C`.
 I don't think to use this library from Objective-C. 😢

**Comment by Datadriven** [comment]
@naru-jpn I was able to use this library for transition between 2 objective c controllers and it works beautifully after a few changes, thank you for sharing this library, I do have one issue that if orientation changes on the presented view controller then while going back to presenting view controller the orientation is not reflected on presenting view controller. Can you please share a solution or any idea how to fix this issue. 

Thanks.

**Comment by naru-jpn** [comment]
@Datadriven That's good!! 🌟 

I haven't enough consider about device orientation. I will see it and I am glad if you create new issue about device orientation! 💨

**Comment by naru-jpn** [comment]
Close issue because inactivity.
