### ISSUE TITLE
'present(viewController:on:attached:completion:)' is unavailable

### ISSUE THREAD

**Issue by alexsanderkhitev** [naru-jpn/View2ViewTransition#30]
Hello! Thanks for this framework.

Please help me, I faced with this error 'present(viewController:on:attached:completion:)' is unavailable

So I'm trying to execute code 

```
let transitionController = TransitionController()
        let imagePickerController = UIImagePickerController()
        imagePickerController.sourceType = .photoLibrary
        imagePickerController.modalPresentationStyle = .overFullScreen
        imagePickerController.transitioningDelegate = transitionController
        
        transitionController.present(viewController: imagePickerController, on: self, attached: imagePickerController, completion: nil)
```

How can I fix it? Thanks

**Comment by otymartin** [comment]
@alexsanderkhitev so what was the problem and solution?

**Comment by otymartin** [comment]
Ok problem is calling this method on a VC that does not conform to `View2ViewTransitionPresenting` protocol.

Solution is to call it on a VC that conforms to that protocol.
