### ISSUE TITLE
IGListKit

### ISSUE THREAD

**Issue by otymartin** [naru-jpn/View2ViewTransition#36]
@naru-jpn can this be used with IGListKit?
Would appreciate a demo re-created using IGListKit
Specifically, getting the initialFrame and initialView from an IGListKit section is tricky.

**Comment by naru-jpn** [comment]
@otymartin 
Sorry my lately response!
I'm not sure this library can be used with IGListKit.

If transition don't work well, you can use debug mode and you can see detail of problem on transition in Xcode console. Please check also readme.

Thanks! 🌟

**Comment by otymartin** [comment]
@naru-jpn 
It works to transition to new VC but pan to dismiss doesnt work.

**Comment by naru-jpn** [comment]
@otymartin I released new version! 
Write new issue if you meet any problems. 🙏
