### ISSUE TITLE
Method "present" is not available in Objective-C 

### ISSUE THREAD

**Issue by kronik** [naru-jpn/View2ViewTransition#37]
Hi! 

found that method:

`public func present(viewController presentedViewController: UIViewController, on presentingViewController: UIViewController, attached: UIViewController, completion: (() -> Void)?) ...`

is marked as unavailable.

How can we use this component in Objective-C?

**Comment by naru-jpn** [comment]
@kronik Thanks!
You probably can not call this library from Objective-C because no `@objc` annotation. That is so old part of this library. 
Please write new issue 'cannot call from Objective-C' if needed, or send your PR! 😃
