### ISSUE TITLE
Does not work with UINavigationController-based transitions

### ISSUE THREAD

**Issue by a2** [naru-jpn/View2ViewTransition#4]
I noticed that you've only implemented the transition for modal view controller presentation. It would be awesome if you could support the `UINavigationControllerDelegate`-based transitions. For example, instead of a new view controller being presented modally, it's pushed onto the navigation controller stack. There are two methods to support this:

- `-navigationController:animationControllerForOperation:fromViewController:toViewController:`
- `-navigationController:interactionControllerForAnimationController:`

**Comment by naru-jpn** [comment]
@a2 Thanks! Yes, this library is not implemented for push/pop transition. Currently I don't know that is practicable in this library but I want to try it.

**Comment by a2** [comment]
I've started working internally on a similar library, except it uses `UINavigationController` instances instead of modal presentation. If circumstances allow, I would like to open source it.

**Comment by naru-jpn** [comment]
@a2 If you re-edit this library, please conform `MIT License` ! 🙌  I also welcome your contribution for this library.

**Comment by a2** [comment]
@naru-jpn The library I'm working on is for my employer and completely separate. (I started working on it before a friend sent me a link to your library.)

**Comment by naru-jpn** [comment]
@a2 I see. In case only concept is similar to this library, you need not to conform any license. Wish you good luck😃

**Comment by kronik** [comment]
@a2 @naru-jpn Hey guys, take a look on my pull request. I've implemented UINavigationController-based transitions because I'm using it in my project. @naru-jpn Awesome code and component 👍🏻!

**Comment by naru-jpn** [comment]
@kronik Thanks!! I checked and commented! ( I know your library `DKLiveBlur` and stared :star2:  )

**Comment by kronik** [comment]
@naru-jpn appreciate if you could take all the code you think might suit your library and merge it

**Comment by naru-jpn** [comment]
Added to support.
