### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [naru-jpn/View2ViewTransition#6]
Hi
Below the title please add badges for carthage compatibility,  pod version, Swift version, license and platform like this:
[![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage) ![Pod Version](https://img.shields.io/badge/Pod-0.0.3-blue.svg) ![Swift Version](https://img.shields.io/badge/Swift-2.2-orange.svg) ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg) ![Plaforms](https://img.shields.io/badge/Platform-iOS-lightgrey.svg)

**Comment by naru-jpn** [comment]
@TofPlay I accepted. Thanks your suggestion!
